In [1]:
# make_classification dataset

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# Display plots directly inside the notebook
%matplotlib inline

In [4]:
# dataset from the sklearn
from sklearn.datasets import make_classification

In [5]:
## create the dataset
X, y = make_classification(n_samples=1000, n_features=10, n_classes=2, random_state=15)

In [6]:
# splitting into trin test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [7]:
# Model training and predict
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)
print(y_pred)

[0 0 0 1 1 0 0 1 1 1 1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 0 0 0 0 1 1 0 1 1 1 0 1
 1 0 0 0 0 0 1 0 1 1 1 1 0 1 1 1 1 1 1 0 0 1 0 1 0 0 0 1 1 0 0 1 0 0 0 1 0
 1 0 1 0 0 0 0 0 0 0 1 0 1 0 0 1 1 1 0 1 1 1 0 1 1 1 1 0 0 0 0 0 1 0 0 0 1
 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 1 1 0 0 0 1 1
 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 0 0 1 0 1 1 0 1 1 0 0 1 1 0 1 0 1 0
 0 1 1 0 1 1 1 1 0 1 1 1 1 1 0]


In [8]:
# metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.93
[[96  5]
 [ 9 90]]
              precision    recall  f1-score   support

           0       0.91      0.95      0.93       101
           1       0.95      0.91      0.93        99

    accuracy                           0.93       200
   macro avg       0.93      0.93      0.93       200
weighted avg       0.93      0.93      0.93       200



In [34]:
# imp-> if the accuracy is less means less than 75% then go with the tuning
# Hyper Parameter Tuning
# Hyperparameters = values you set before training
# Goal is to Find best combination → best model performance

# 1️⃣ Grid Search
# 👉 Tries all possible combinations
# ✅ Best for:
# Small datasets
# Few hyperparameters
# When you want guaranteed best result
# ❌ Not good for:
# Large search space (very slow)

# 2️⃣ Random Search

# 👉 Tries random combinations

# ✅ Best for:
# Large datasets
# Many hyperparameters
# When time is limited

# 3️⃣ Bayesian Optimization

# 👉 Smart search (learns from previous results)

# Chooses next best parameters based on past performance
# ✅ Best for:
# Expensive models (deep learning, XGBoost)
# When you want efficient optimization

# 4️⃣ Gradient-Based Optimization

# 👉 Used in:

# Neural Networks

# Example:

# learning rate tuning during training

In [28]:
# Grid Search CV params
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

param_grid = [

    # 🔹 L1 penalty
    {
        'penalty': ['l1'],
        'C': [100,10,1.0,0.1,0.001],
        'solver': ['liblinear', 'saga']
    },

    # 🔹 L2 penalty
    {
        'penalty': ['l2'],
        'C': [100,10,1.0,0.1,0.001],
        'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']
    },

    # 🔹 ElasticNet
    {
        'penalty': ['elasticnet'],
        'C': [100,10,1.0,0.1,0.001],
        'solver': ['saga'],
        'l1_ratio': [0.5, 0.7, 0.9]   # MUST include
    }
]

In [29]:
# Stratified K fold
from sklearn.model_selection import StratifiedKFold
skfcv = StratifiedKFold()

In [30]:
# Grid Search CV
from sklearn.model_selection import GridSearchCV
grid_search = GridSearchCV(estimator=model,param_grid=param_grid,scoring='accuracy',cv=skfcv,n_jobs=-1)

In [31]:
grid_search

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid=[{'C': [100, 10, 1.0, 0.1, 0.001], 'penalty': ['l1'],
                          'solver': ['liblinear', 'saga']},
                         {'C': [100, 10, 1.0, 0.1, 0.001], 'penalty': ['l2'],
                          'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                     'saga']},
                         {'C': [100, 10, 1.0, 0.1, 0.001],
                          'l1_ratio': [0.5, 0.7, 0.9],
                          'penalty': ['elasticnet'], 'solver': ['saga']}],
             scoring='accuracy')

In [32]:
grid_search.fit(X_train, y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid=[{'C': [100, 10, 1.0, 0.1, 0.001], 'penalty': ['l1'],
                          'solver': ['liblinear', 'saga']},
                         {'C': [100, 10, 1.0, 0.1, 0.001], 'penalty': ['l2'],
                          'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                     'saga']},
                         {'C': [100, 10, 1.0, 0.1, 0.001],
                          'l1_ratio': [0.5, 0.7, 0.9],
                          'penalty': ['elasticnet'], 'solver': ['saga']}],
             scoring='accuracy')

In [33]:
grid_search.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'liblinear'}

In [35]:
# predict
y_pred = grid_search.predict(X_test)
print(y_pred)

[0 0 0 1 1 0 0 1 1 1 1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 0 0 0 0 1 1 0 1 0 1 0 1
 1 0 0 0 0 0 1 0 1 1 1 1 0 1 1 1 1 1 1 0 0 1 0 1 0 0 0 1 1 0 0 1 0 0 0 1 0
 1 0 1 0 0 0 0 0 0 0 1 0 1 0 0 1 1 1 0 1 1 1 0 1 1 1 1 0 0 0 0 0 1 0 0 0 1
 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 1 0 0 1 1 1 1 0 0 0 1 1
 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 0 0 1 0 1 1 0 1 1 0 0 1 1 0 1 0 1 0
 0 1 1 0 1 1 1 1 0 1 1 1 1 1 0]


In [36]:
# metrics
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.94
[[98  3]
 [ 9 90]]
              precision    recall  f1-score   support

           0       0.92      0.97      0.94       101
           1       0.97      0.91      0.94        99

    accuracy                           0.94       200
   macro avg       0.94      0.94      0.94       200
weighted avg       0.94      0.94      0.94       200



In [37]:
# without tuning 93% now after tuning 94%

In [39]:
# same thing for Randomized search cv
from sklearn.model_selection import RandomizedSearchCV
random_search=RandomizedSearchCV(estimator=model,param_distributions=param_grid,scoring='accuracy',cv=skfcv,n_jobs=-1)#(n_jobs=-1)-> how many CPU core use

In [40]:
random_search.fit(X_train,y_train)

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
                   estimator=LogisticRegression(), n_jobs=-1,
                   param_distributions=[{'C': [100, 10, 1.0, 0.1, 0.001],
                                         'penalty': ['l1'],
                                         'solver': ['liblinear', 'saga']},
                                        {'C': [100, 10, 1.0, 0.1, 0.001],
                                         'penalty': ['l2'],
                                         'solver': ['newton-cg', 'lbfgs',
                                                    'liblinear', 'sag',
                                                    'saga']},
                                        {'C': [100, 10, 1.0, 0.1, 0.001],
                                         'l1_ratio': [0.5, 0.7, 0.9],
                                         'penalty': ['elasticnet'],
                                         'solver': ['saga']}],
                   scoring='accuracy')

In [41]:
# metrics
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.94
[[98  3]
 [ 9 90]]
              precision    recall  f1-score   support

           0       0.92      0.97      0.94       101
           1       0.97      0.91      0.94        99

    accuracy                           0.94       200
   macro avg       0.94      0.94      0.94       200
weighted avg       0.94      0.94      0.94       200

